services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=postgres
      - DB_PORT=5432
      - PORT=${PORT}
    ports:
      - '${PORT}:3000'
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Serve per evitare problemi con i moduli npm nel container
    command: npm run dev # Serve per usare nodemon per lo sviluppo
    networks:
      - my_network

  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/config:/docker-entrypoint-initdb.d/
    networks:
      - my_network

volumes:
  db_data:

networks:
  my_network:
    driver: bridge
